# CD script to deploy project to Firebase on push to main branch
name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    # Ubuntu is cheaper to use than Windows or macOS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - run: npm ci
    - run: npm run build
      # Exisiting Action that acts as library for Firebase
    - uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
