# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Ubuntu is cheaper to use than Windows or macOS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: |
            npm ci
            cd functions
            npm ci
    - name: Run linter
      run: |
            npm run lint
            cd functions
            npm run lint
    - name: Build project
      run: |
            npm run build --if-present
            cd functions
            npm run build --if-present
    - name: Run tests
      run: npm test
    - name: Test running functions from GitHub
      run: |
            cd functions
            firebase functions:config:get
